/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.horoscopo;

/**
 *
 * @author jc111
 */
public class frmhoroscopo extends javax.swing.JFrame {

    /**
     * Creates new form frmhoroscopo
     */
    public frmhoroscopo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        Bcalcular = new javax.swing.JButton();
        Bnuevo = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        txtresultado = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar Dia:");

        jLabel2.setText("Ingresar Mes:");

        Bcalcular.setText("Calcular Signo");
        Bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcalcularActionPerformed(evt);
            }
        });

        Bnuevo.setText("Nuevo");
        Bnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnuevoActionPerformed(evt);
            }
        });

        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        txtresultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado Horoscopo"));

        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Bcalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(txtMes))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsalir)
                    .addComponent(Bcalcular))
                .addGap(44, 44, 44)
                .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcalcularActionPerformed
        // TODO add your handling code here:
        // DECLARACION DE VARIABLES Y USAMOS CONDICIONES
        
        int dia=Integer.parseInt(txtDia.getText());
        int mes=Integer.parseInt(txtMes.getText());
        
        switch (mes) {
                    case 1:
                        System.out.println("Tu eres de Enero");
                        if (dia >= 1 && dia <= 20) {
                            txtresultado.setText("Capricornio");
                        } else if (dia > 20 && dia <= 31) {
                            txtresultado.setText("Acuario");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 2:
                        System.out.println("Febrero");
                        if (dia >= 1 && dia < 20) {
                            txtresultado.setText("Acuario");
                        } else if (dia >= 20 && dia <= 28) {
                            txtresultado.setText("Piscis");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 3:
                        System.out.println("Marzo");
                        if (dia >= 1 && dia <= 20) {
                            txtresultado.setText("Piscis");
                        } else if (dia > 20 && dia <= 31) {
                            txtresultado.setText("Aries");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 4:
                        System.out.println("Abril");
                        if (dia >= 1 && dia <= 20) {
                            txtresultado.setText("Aries");
                        } else if (dia > 20 && dia < 31) {
                            txtresultado.setText("Tauro");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 5:
                        System.out.println("Mayo");
                        if (dia >= 1 && dia <= 21) {
                            txtresultado.setText("Tauro");
                        } else if (dia >= 22 && dia <= 31) {
                            txtresultado.setText("Geminis");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 6:
                        System.out.println("Junio");
                        if (dia >= 1 && dia <= 21) {
                            txtresultado.setText("Geminis");
                        } else if (dia >= 22 && dia <= 30) {
                            txtresultado.setText("Cancer");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 7:
                        System.out.println("Julio");
                        if (dia >= 1 && dia <= 22) {
                            txtresultado.setText("Cancer");
                        } else if (dia >= 23 && dia <= 31) {
                            txtresultado.setText("Leo");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 8:
                        System.out.println("Agosto");
                        if (dia >= 1 && dia <= 23) {
                            txtresultado.setText("Leo");
                        } else if (dia >= 24 && dia <= 31) {
                            txtresultado.setText("Virgo");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 9:
                        System.out.println("Septiembre");
                        if (dia >= 1 && dia <= 23) {
                           txtresultado.setText("Virgo");
                        } else if (dia >= 24 && dia <= 30) {
                            txtresultado.setText("Libra");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 10:
                        System.out.println("Octubre");
                        if (dia >= 1 && dia <= 23) {
                            txtresultado.setText("Libra");
                        } else if (dia >= 24 && dia <= 31) {
                            txtresultado.setText("Escorpio");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 11:
                        System.out.println("Noviembre");
                        if (dia >= 1 && dia <= 22) {
                            txtresultado.setText("Escorpio");
                        } else if (dia >= 23 && dia <= 30) {
                            txtresultado.setText("Sagitario");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    case 12:
                        System.out.println("Diciembre");
                        if (dia >= 1 && dia <= 21) {
                            txtresultado.setText("Sagitario");
                        } else if (dia >= 22 && dia <= 31) {
                            txtresultado.setText("Capricornio");
                        } else {
                            System.out.println("Te saliste del rango");
                        }
                        break;
                    default:
                        System.out.println("Por favor ingrese un mes valido");
                        break;
                }
        
        
        
        
        /*if(dia>=21 && mes.equals("Marzo")||dia<=20 &&mes.equals("Abril")){
            txtresultado.setText("Aries");
    }else if(dia>=21 &&mes.equals("Abril")||dia<=20&&mes.equals("Mayo")){
        txtresultado.setText("Tauro");       
    }else if(dia>=21 &&mes.equals("Mayo")||dia<=20&&mes.equals("Junio")){
       txtresultado.setText("Geminis");
    }else if(dia>=22 &&mes.equals("Junio")||dia<=22&&mes.equals("Julio")){
        txtresultado.setText("Cancer");
    }else if(dia>=23 &&mes.equals("Julio")||dia<=22&&mes.equals("Agosto")){
        txtresultado.setText("Leo");
    }else if(dia>=23 &&mes.equals("Agosto")||dia<=22&&mes.equals("Septiembre")){
        txtresultado.setText("Virgo");
    }else if(dia>=23 &&mes.equals("Septiembre")||dia<=22&&mes.equals("Octubre")){
        txtresultado.setText("Libra");
    }else if(dia>=23 &&mes.equals("Octubre")||dia<=21&&mes.equals("Noviembre")){
        txtresultado.setText("Escorpio");
    }else if(dia>=22 &&mes.equals("Noviembre")||dia<=21&&mes.equals("Dicimbre")){
        txtresultado.setText("Sagitario");
    }else if(dia>=22 &&mes.equals("Diciembre")||dia<=20&&mes.equals("Enero")){
        txtresultado.setText("Capricornio");
    }else if(dia>=21 &&mes.equals("Enero")||dia<=19&&mes.equals("Febrero")){
        txtresultado.setText("Acuario");
    }else if(dia>=20 &&mes.equals("Febrero")||dia<=20&&mes.equals("Marzo")){
        txtresultado.setText("Piscis");
    } */  
     
        
    }//GEN-LAST:event_BcalcularActionPerformed

    private void BnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnuevoActionPerformed
        // TODO add your handling code here:
        txtDia.setText(null);
        txtMes.setText(null);
    }//GEN-LAST:event_BnuevoActionPerformed

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmhoroscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmhoroscopo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcalcular;
    private javax.swing.JButton Bnuevo;
    private javax.swing.JButton Bsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JLabel txtresultado;
    // End of variables declaration//GEN-END:variables
}
